#!/bin/bash

declare -a urls=(
"https://github.com/edwardtufte/presenter/blob/e1ab0b1d09d928ca7914b0c5cc0e253dcd27e12b/font/et-bembo/source/4-ttf/ETBembo-RomanLF.ttf"
)

fonts_dir="${HOME}/.local/share/fonts/"

if [[ ! -d "$fonts_dir" ]]; then
    mkdir -p "$fonts_dir"
fi

for url in "${urls[@]}"; do
    filename="${url##*/}"
    echo "Downloading $filename"
    wget "$url"
    mv "$filename" "$fonts_dir"
done

fc-cache -fv
