#+title: Readme

* Quick start

1. Acquire a NixOS 24.05+ image:
#+begin_src shell
wget -O nixos.iso https://channels.nixos.org/nixos-unstable/latest-nixos-minimal-x86_64-linux.iso
#+end_src

2. Write it to a USB drive:
#+begin_src shell
# Replace /dev/sdX with the correct partition!
cp nixos.iso /dev/sdX
#+end_src

3. Restart and boot into the installer.

4. Do your partitions and mount your root to ~/mnt~

5. Clone these dotfiles somewhere:
#+begin_src shell
git clone --recurse-submodules https://github.com/lejeunel/dotfiles
#+end_src

6. Create a host config in ~hosts/~

7. Run the installer:
#+begin_src shell
sudo nixos-install \
    --impure \
    --show-trace \
    --root /mnt \
    --flake .#host
#+end_src

Where host corresponds to a host defined in ~hosts/~

8. Copy dotfiles over to new partition
#+begin_src shell
sudo mkdir -p /mnt/etc/nixos
sudo cp -R $PWD /mnt/etc/nixos/dotfiles
#+end_src

8. Then reboot and you're good to go!

[!WARNING]
Don't forget to change your ~root~ and ~$USER~ passwords! They are set to
~nixos~ by default.

* Commands

** Rebuilding system

#+begin_src shell
nh os switch -u ~/dotfiles
#+end_src

** Apply Home-Manager configuration

See Makefile.

** Cleaning old generations

#+begin_src shell
nh clean all
#+end_src


** Enabling experimental features globally when installing from standalone home-manager
#+begin_src shell
echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
#+end_src

* Secrets
** Email Accounts
I use [[https://www.passwordstore.org/][pass]] to manage passwords.
In particular, ~msmtp~ retrieves emails by invoking the ~pass~
command to get passwords.

This therefore requires to setup the passwords manually
using:

- ~pass init~ to initialize a new keyring
- ~pass insert~ to add a new password that will be used by
  downstream apps.
* Resources
- i3, doom emacs: [[https://github.com/kenranunderscore/dotfiles/blob/bb0d038f1f31d52acef0da777621dfc1ea4b8a6d/modules/doom/default.nix][kenranunderscore/dotfiles]]
- https://github.com/doomemacs/doomemacs/blob/master/shell.nix
- [[https://github.com/vimjoyer/nixconf.git]]
