#+title: Readme

* Commands
** Rebuilding system
From project's root:

#+begin_src shell
nh os switch .
#+end_src

** Apply Home-Manager configuration

From project's root:

#+begin_src shell
nh home switch .
#+end_src

** Cleaning old generations

#+begin_src shell
nh clean all
#+end_src

** Enabling experimental features globally when installing from standalone home-manager
#+begin_src shell
echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf
#+end_src

* Secrets
I use [[https://github.com/Mic92/sops-nix][sops-nix]] to encrypt and decrypt secrets
using the public/private key-file
located at ~/home/laurent/.config/sops/age/keys.txt~.

~<PROJECT-ROOT>/secrets.yaml~ contains all encrypted secrets.

* Updating
The ~flake.lock~ file contains the commit hash of
the nixpkgs/nixos-unstable repository used to construct
this system.

Run ~nix flake update~ from project's root to update
all packages to their latest version.

Last, re-build using the ~switch~ commands.

* Installing NixOS

1. Acquire a NixOS 24.05+ image:
#+begin_src shell
wget -O nixos.iso https://channels.nixos.org/nixos-unstable/latest-nixos-minimal-x86_64-linux.iso
#+end_src

2. Write it to a USB drive:
#+begin_src shell
# Replace /dev/sdX with the correct partition
cp nixos.iso /dev/sdX
#+end_src

3. Restart and boot into the installer.

4. Do your partitions and mount your root to ~/mnt~

5. Clone these dotfiles:
#+begin_src shell
git clone --recurse-submodules https://github.com/lejeunel/dotfiles /home/laurent
#+end_src

6. Create a host config in ~hosts/~

7. Run the installer:
#+begin_src shell
sudo nixos-install \
    --impure \
    --show-trace \
    --root /mnt \
    --flake .#host
#+end_src

Where host corresponds to a host defined in ~hosts/~

8. Copy dotfiles over to new partition
#+begin_src shell
sudo mkdir -p /mnt/etc/nixos
sudo cp -R $PWD /mnt/etc/nixos/dotfiles
#+end_src

8. Then reboot and you're good to go!

[!WARNING]
The ~root~ and ~$USER~ passwords are both set to ~nixos~ by default.
Make sure to change them!

* Resources
- i3, doom emacs: [[https://github.com/kenranunderscore/dotfiles/blob/bb0d038f1f31d52acef0da777621dfc1ea4b8a6d/modules/doom/default.nix][kenranunderscore/dotfiles]]
- https://github.com/doomemacs/doomemacs/blob/master/shell.nix
- [[https://github.com/vimjoyer/nixconf.git]]
