set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"
set -g prefix C-a
set -g base-index 1

# Set 'v' for vertical and 'h' for horizontal split
bind v split-window -h -c '#{pane_current_path}'
bind h split-window -v -c '#{pane_current_path}'

bind-key "k" display-popup -E -w 40% "sesh-connect"
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session


set -g mouse on

set-window-option -g mode-keys vi


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

set -sg escape-time 0

# don't rename windows automatically
set-option -g allow-rename off

set -g history-limit 100000

######################
### DESIGN CHANGES ###
######################

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour9 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour154'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour7 fg=colour137 dim'
set -g status-left-length 20

setw -g window-status-current-style 'fg=colour9 bg=colour2 bold'
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour0]#W#[fg=colour249]#F '

setw -g window-status-style 'fg=colour9 bg=colour3'
setw -g window-status-format ' #I#[fg=colour249]:#[fg=colour0]#W#[fg=colour249]#F '

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# messages
set -g message-style 'fg=colour30 bg=colour16 bold'
