#!/usr/bin/env bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PROG=$( basename "$0" )

# config file:
CFG_FILE=${XDG_CONFIG_DIR:-$HOME/.config}/$PROG/config

DEFAULT_CONFIG='
MYLOCK_TIMEOUT_LOCK=300
MYLOCK_TIMEOUT_TURNOFF=400
MYLOCK_TIMEOUT_SUSPEND=405
BINDINGS_FILE=${XDG_CONFIG_DIR:-$HOME/.config}/sway/config
VERBOSE=""
'

eval "$DEFAULT_CONFIG"

MODES="\
lock-now:    lock the screen
safe:        auto-blanking, auto-lock & auto-suspend (default mode after boot or suspend)
movie:       no auto-blanking, auto-lock or auto-suspend
"

usage() {
    cat << EOF
Usage: $PROG [OPTIONS] [seconds] [mode [mode ...]]

Set up swayidle with automatic screen blanking, lock and/or suspend
after an idle period according to your desired 'mode':

safe          should be the default at startup in the sway config.
movie         at home watching a movie - no suspend nor locking nor blanking

You can put default settings in the config file $CFG_FILE

OPTIONS:

-c|--config <file>   config file

-q|--quiet           don't popup confirmation dialog
                     Or put QUIET=true in the config file.

-n|--no-notify       don't send notification
                     Or put NOTIFY="" in the config file.

-p|--print-status print the current arguments of swayidle (as the
                     output of ps is not very helpful)

-m|--mode print the current mode

-C|--countdown <secs>
                     Countdown to locking/suspend (requires sway-count +
                     nwg-wrapper). Or put COUNTDOWN=<secs> in the config file.
                     NB Countdown in the lockscreen is only supported with

-v|--verbose         Be verbose

'seconds' is the time before an idle event is triggered (default 600 = 10m)
Or put MYLOCK_TIMEOUT=<seconds> in the config file.

'mode' is one of:
$MODES

If no argument is given then a wofi dialog pops up to select one of
the above modes.

In all modes (except movie), the screen is blanked after the
first timeout. Locking, if enabled, happens on the next timeout and
then suspend, if enabled. For all modes, after a suspend, safe-mode is
enabled and the screen is locked.

Dependencies: rofi, swayidle, swaylock.

I suggest the following key bindings and startup for sway's config file:

# this first one pops up the dialog to select the mode:
bindsym  \$mod+l                exec $PROG
bindsym  Shift+\$mod+l          exec $PROG at-home-mode
bindsym  Control+\$mod+l        exec $PROG safe-mode
bindsym  Control+Shift+\$mod+l  exec $PROG lock-now
...

It is recommended to have the following in your sway config to start
swayidle with safe defaults:

exec $PROG safe-mode
or
exec $PROG desktop

Sample config file:
$DEFAULT_CONFIG
EOF
}

# defaults:
SELF=$0
WAIT='-w'
VERBOSE=""

[[ -r "$CFG_FILE" ]] && source "$CFG_FILE"

# process options:
TEMP=$( getopt --options c:dhi:pqnmrC:v --longoptions config:,help,image:,print,quiet,mode,no-notify,random,countdown:,verbose -- "$@" ) || exit 1
eval set -- "$TEMP"

CFG_OPT=
Q_OPT=
V_OPT=
for i in "$@"; do
    case $i in
        -c|--config)
            # load settings from config file:
            CFG_FILE="$2"
            CFG_OPT="-c $CFG_FILE"
            shift 2
            ;;

        -q|--quiet)
            Q_OPT="-q"
            shift
            ;;
        -h|--help) usage; exit 0;;
        -v|--verbose)
            VERBOSE="set"
            V_OPT="-v"
            shift
            ;;
        --) shift; break;;
    esac
done

type "$PROG" &>/dev/null || PATH+=":$( dirname "$0" )"


[[ "$VERBOSE" ]] && set -x


swaymsg -q "output * power on"

ALL_OPTS="$CFG_OPT $Q_OPT $V_OPT"
do_suspend="$SELF $ALL_OPTS safe; systemctl suspend"


while [[ "$1" ]]; do
    MODE="$1"
    shift
    case "$MODE" in
        "lock-now"*)

            swaylock -f --clock --indicator
            ;;

        "safe"*)
            pkill -u "$USER" -9 swayidle
            swayidle $WAIT \
                  timeout "$MYLOCK_TIMEOUT_LOCK"    "swaylock -f --clock --indicator" \
                  timeout "$MYLOCK_TIMEOUT_TURNOFF" "swaymsg -q 'output * power off'" \
                  timeout "$MYLOCK_TIMEOUT_SUSPEND" "sudo $do_suspend" \
                  resume                            "swaymsg -q 'output * power on'" \
                  before-sleep                      "$SELF lock-now"
            ;;

        "home"*)
            pkill -u "$USER" -9 swayidle
            swayidle $WAIT \
                  timeout "$MYLOCK_TIMEOUT_TURNOFF" "swaymsg -q 'output * power off'" \
                  timeout "$MYLOCK_TIMEOUT_SUSPEND" "sudo $do_suspend" \
                  resume                            "swaymsg -q 'output * power on'" \
            ;;

        "movie"*)
            pkill -u "$USER" -9 swayidle
            ;;

        *)
            echo "$PROG: no such locking mode '$MODE'" >&2
            exit 1
            ;;
    esac
done

exit 0
