# Commands go through bash
shell = "bash -c '{}'"

[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"

[[item]]
file = "~/.config/waybar/colors.css"
template = "waybar"
hook = "pkill -SIGRTMIN+7 waybar"
rewrite = true

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[item]]
file = "~/.config/qutebrowser/config.py"
template = "qutebrowser"
subtemplate = "minimal"
hook = "reloadqb"

[[item]]
file= "~/.config/zathura/zathurarc"
template = "zathura"

[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true
hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme FlatColor"

# Sway supports the default '#' comments, so it can be ommited
# 'rewrite' is also ommited, as it defaults to false
[[items]]
file = "~/.config/sway/config"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not light
light = false
