hide_edge_borders smart
default_border pixel 4
titlebar_border_thickness 0
gaps inner 15px
default_dim_inactive 0.1
smart_gaps on
smart_corner_radius on
corner_radius 4
blur enable
shadows enable
blur_passes 2
blur_radius 2
layer_effects "waybar" "blur enable"; shadows enable
shadow_blur_radius 20
