set $gnome-schema org.gnome.desktop.interface

exec_always {
    gsettings set $gnome-schema gtk-theme 'Dracula'
    gsettings set $gnome-schema icon-theme 'Dracula'
    gsettings set $gnome-schema cursor-theme 'xcursor-breeze'
    gsettings set $gnome-schema font-name 'Cantarell 14'
}
