# autostart background applications
#exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# autostarts
exec {
    $xdg-dirs
    $swaync
    # $swappy_notify
    $autostart_dex
    # $flashfocus
    # $wlsunset
    $cliphist_store
    $cliphist_watch
    $workspace_icons
    $locking
    # $statusbar
}

exec_always {
    $kanshi
    # $auto_xdg_keyboard
    # $poweralert
    # $watch_playerctl
    $swayidle
    $calendar_daemon
    $swayr_daemon
}
