# autostart background applications
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# autostarts
exec {
    $xdg-dirs
    $swayidle
    $swaync
    $swappy_notify
    $autostart_dex
    $flashfocus
    $wlsunset
    $cliphist_store
    $cliphist_watch
    $workspace_icons
    $mounting_daemon
}

exec_always {
    $kanshi
    $auto_xdg_keyboard
    $poweralert
    $watch_playerctl
    $calendar_daemon
    $swayr_daemon
}
