lastupdatecheck: 0
recentrepos:
- /home/laurent/.dotfiles
- /home/laurent/Documents/code/go-bookstore
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
